---

stages:
  - compile
  - test
  - name: deploy
    if: branch = master

language: node_js
node_js:
- '10'
- '12'
- '14'
after_success:
  - yarn run coverage
  - yarn run build:docs

notifications:
  webhooks:
    urls:
      secure: oQkU0NJIM7TDT7fNLS9T1Z9Su4md4vj5xoi21Gu9iMmmsj8H1GTLfSPoN1r++olRVoUf26qxd7fAiDkAAuIcgT02OlTRm2PBNWYvzY8LYAbWJXfyexclNlGg1T1o92lewZ/bqAKKBlD2NDwieXxatueeiNn74O8aQSL31GRpo4c0ls3O3msfYNA3qk871T0B7jnrJ+ipB4BF5X76EKMwgtfRYV2LC//CAsicvXiabno2XPy7DbdPE+oVEQ4pUANW0MbRN3+yyVt95RNlJMhp32xts2RivJV5VMkQF79s2lg1+0N75joFLfuo9WEuQQmKR5vgUeU2wFdV3Mv/yh3rz06uCwWcqPZ4V/vcfiNjFewLFeBAAufAZO55ckHneuGpJAURClzdWbRgXQcvTAviiih8s57ccmUaegcrC/gtzo8/YkSg8/2VZp79edo9Kh5YJU+v93foqvvQRKWTBteku1JavwJHZL44XKSpKuylay6axY6r/5EMtio5q/WIldDB1faPcMYb6v7tzvzHq9/dDr4UjLyKgPdwxEBJhrYFSAWWed+jQ6XLlYtW23uWrhshYCuuX0o4VpHcNTFyAfGhwIAq7qIm8xdMb0x2NEbmqXtUG69DyZsqFVG0lYkLAN5FkvpWELVtPVdJA8KM9v7iy82+Hs1Hut1lIVZkZk4XWPA=
    on_success: change
    on_failure: always
    on_start: never
env:
  global:
    secure: cVh9zZxzLid/UW+ulDQsSlXD1lxpZVnR+GjTQmXL64DoNAM6KFcITTXi+lDCY1YLSgcVyUUBqPuUEF9AYJ6TUo/cvrsP0eo5EmEkISU77DpF4DwY+47wrj9hbTv7RynmNtKW3csqgtz3cjiAEkISr3lHk4drNO224kdS0k4CUZ4bshMc5LZrExbi+ZRbwxF186ibHWhfNMg/k+pLT35tGgx5OOybCweeizDtiTvwNwkSS1hchzxa2slwrKLUzq0U4yHsu7zBJC3S2o5yN3xJReKmq8YO/bdFU10t/8HDrss5PC1dE1jYyfkw640qpLHvOxcXR+b4ENPVaMCz9x1UavdCcnV6MzoAoNHkF+raapnUqd6a897eLatmLUVSmtrVdh+Nf6ln361LVvEpk+vOTQK5v/fFnwUGdPtEv0bk2u2uEc95Ed3KhjCnxpcMgPbtJZkFy2Hg6s4hHuC5o93NV7/xVlWZOV8uFAvRXrhTzLUPnhbB9hklRqSNaZUpYjiccvotw4/YLQEqgb2ORyXyN+R3bcyBirHYq2aJWJHYwPh7y65QCh4+3wqeLMQHCcgEeuWEKwm8FcfvXXftbW+gTRr5EUyUYsBzIqxaM01QfQvWtTukZ3woErd3WDZ7hLLHUvciBHIGM4E+yvcZbPfUwKxhDLLgwRk9Zi0Yh+Lm5EE=

jobs:
  include:
    - stage: deploy
      name: Deploy Documentation
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        on:
        branch: master
        local_dir: documentation
