version: 2.1

executors:
  node:
    resource_class: small
    parameters:
      tag:
        type: string
        default: lts
    docker:
      - image: circleci/node:<< parameters.tag >>
    working_directory: ~/sprache
    

orbs:
  node: circleci/node@2.0.0
  codecov: codecov/codecov@1.1.1

commands:
  save-workspace:
    parameters:
      attach_path:
        type: string
        default: ~/sprache
    steps:
      - persist_to_workspace:
          root: <<parameters.attach_path>>
          paths:
            - "dist"
            - "documentation"
            - "coverage"
            - "junit.xml"
  load-workspace:
    parameters:
      attach_path:
        type: string
        default: ~/sprache
    steps:
      - checkout
      - attach_workspace:
          at: <<parameters.attach_path>>
  yarn-install:
    steps:
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-

      - run: yarn --frozen-lockfile --cache-folder ~/.cache/yarn

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
  build:
    steps:
      - run: yarn build
      - run: yarn build:docs
  test-ci:
    parameters:
      store-results:
        type: boolean
        default: true
    steps:
      - run: yarn test:ci
      - when:
          condition: << parameters.store-results >>
          steps:
            # - store_artifacts:
            #     path: coverage
            - store_test_results:
                path: test-results
            - codecov/upload:
                file: coverage/lcov.info

jobs:
  build:
    executor: node
    steps:
      - checkout
      - yarn-install
      - build
      - test-ci
      - save-workspace

  publish:
    executor: node
    steps:
      - load-workspace
      - yarn-install
      - run:
          name: publish
          command: yarn run semantic-release || true

  test:
    parameters:
      node-tag:
        type: string
    executor:
      name: node
      tag: << parameters.node-tag >>
    steps:
      - load-workspace
      - yarn-install
      - test-ci:
          store-results: false

workflows:
  version: 2
  build-publish:
    jobs:
      - build
      - test:
          filters:
            branches:
              only:
                - master
                - develop
          requires:
            - build
          matrix:
            parameters:
              node-tag: ["dubnium", "erbium", "fermium"]
      - publish:
          filters:
            branches:
              only:
                - master
          requires:
            - build