version: 2.1

executors:
  linux:
    docker:
      - image: cimg/base:2020.01

orbs:
  node: circleci/node@2.0.0

jobs:
  build:
    docker:
      - image: cimg/node:lts

    working_directory: ~/sprache

    steps:
      - checkout

      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-

      - run: yarn --frozen-lockfile --cache-folder ~/.cache/yarn

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run: yarn build

      - store_artifacts:
          path: coverage

      - store_test_results:
          path: junit.xml

  publish:
    docker:
      - image: cimg/node:lts

    working_directory: ~/sprache

    steps:
      - checkout

      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-

      - run: yarn --frozen-lockfile --cache-folder ~/.cache/yarn

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run: yarn build
      - run:
          name: publish
          command: yarn run semantic-release --dry-run || true

  test:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
          install-yarn: true
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-

      - run: yarn --frozen-lockfile --cache-folder ~/.cache/yarn
      - run: yarn test:ci

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
          matrix:
            parameters:
              os: [linux]
              node-version: ["10.23.0", "12.19.0", "14.15.0"]
      - publish