version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:lts

    working_directory: ~/sprache

    steps:
      - checkout

      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-

      - run: yarn --frozen-lockfile --cache-folder ~/.cache/yarn

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run: yarn build
      - run: yarn test:ci

      - store_artifacts:
          path: coverage

      - store_test_results:
          path: junit.xml

workflows:
  version: 2
  build-deploy:
    jobs:
      - build